on: push

jobs:
  test:
    runs-on: ubuntu18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: '1.10.3' # Define the elixir version [required]
          otp-version: '22.3' # Define the OTP version [required]
      - run: mix deps.get
      - run: mix test
